### ISSUE TITLE
Resize thumbnail

### ISSUE THREAD

**Issue by rosskukulinski** [cloudytimemachine/worker-screenshot#1]
Currently the worker-screenshot uses Phantomjs to capture a high-resolution screenshot of the page and then uploads that to Google cloud storage.  We also need a lower-resolution thumbnail to use in the frontend.  

We could certainly leverage imagemagic or some other C/C++ image manipulation library, but I'm interested in finding a Javascript-only resize library.  Resizing is CPU intensive and I'd like to demonstrate what CPU bound work looks like when Nodejs is profiled.

Open question:  What does the worker do with the thumbnail?  Should it also be uploaded to Google storage?  Should it be base64 encoded and included with the JSON to the message bus so that it can be shoved into rethinkdb?

**Comment by geojaz** [comment]
Some websites eg: redhat.com have really long pages, so screenshot cannot simply scale the full capture...

 ![image](https://cloud.githubusercontent.com/assets/9451328/17863170/97280336-6866-11e6-975e-dbf3c404c5f2.png)

**Comment by rosskukulinski** [comment]
completed
